name: CI Pipeline

on:
  push:
    branches:
      - main   # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the runner

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'

      # Build the project using Gradle
      - name: Build
        run: ./gradlew assemble

      # Run unit tests
      - name: Test
        run: ./gradlew test
